version: '3.8'

services:
  backend:
    build: .
    container_name: backend_container
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis_container
      REDIS_PORT: 6379
    networks:
      - app_network

  redis:
    image: redis:7.4.2-alpine
    container_name: redis_container
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
